# Autogenerated wrapper script for Soup3_jll for x86_64-apple-darwin
export libsoup

using Glib_jll
using SQLite_jll
using nghttp2_jll
using brotli_jll
using libpsl_jll
using GlibNetworking_jll
JLLWrappers.@generate_wrapper_header("Soup3")
JLLWrappers.@declare_library_product(libsoup, "@rpath/libsoup-3.0.0.dylib")
function __init__()
    JLLWrappers.@generate_init_header(Glib_jll, SQLite_jll, nghttp2_jll, brotli_jll, libpsl_jll, GlibNetworking_jll)
    JLLWrappers.@init_library_product(
        libsoup,
        "lib/libsoup-3.0.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
